### ISSUE TITLE
Why LEDArray does take 192 bytes?

### ISSUE THREAD

**Issue by valeriyvan** [bitbank2/sense_hat_unchained#1]
https://github.com/bitbank2/sense_hat_unchained/blob/1017ecee5caade6057ee7e75c2b2741d938bd605/sensehat.c#L51

8x8 LEDs, each takes 2 bytes.
Where 192 comes from?

**Comment by bitbank2** [comment]
8x8x3 --> each LED specifies a R + G + B value (1 byte each)

**Comment by valeriyvan** [comment]
Color in frame buffer of SenseHat is coded with two bytes. So called RGB565. 5 bits for red, 6 bits for green and 5 bits for blue.

**Comment by bitbank2** [comment]
Yes, the API accepts an RGB565 value, but it gets split into 3 bytes to write it to the sense hat. Each byte only uses the first 6 bits (18 bits per color) inside the sense hat. I figured it would be easier to specify colors this way, but you're welcome to change the function to accept 3 bytes for R/G/B.
